#!/usr/bin/env bash
# End-to-end smoke test. Sends a synthetic message via Omni's documented
# REST API (POST /api/v2/messages/send) and asserts a non-empty response.
#
# Requires OMNI_API_KEY (auto-generated by Omni at first install — read
# from `docker compose exec omni omni config show` or from the .env file
# if you set it explicitly).

set -euo pipefail

OMNI_URL="${OMNI_URL:-http://localhost:8882}"
TEST_PHONE="${TEST_PHONE:-5511999999999}"
TEST_MESSAGE="${TEST_MESSAGE:-ping}"

if [[ -z "${OMNI_API_KEY:-}" ]]; then
    echo "[smoke] set OMNI_API_KEY before running this script" >&2
    echo "[smoke] retrieve it with: docker compose exec omni omni config show" >&2
    exit 1
fi

echo "[smoke] sending '${TEST_MESSAGE}' to ${TEST_PHONE} via ${OMNI_URL}"

response=$(curl -fsSL \
    -X POST \
    -H "Content-Type: application/json" \
    -H "X-API-Key: ${OMNI_API_KEY}" \
    -d "{\"to\":\"${TEST_PHONE}\",\"text\":\"${TEST_MESSAGE}\"}" \
    "${OMNI_URL}/api/v2/messages/send")

echo "[smoke] response: ${response}"

if [[ -z "$response" ]]; then
    echo "[smoke] FAIL: empty response" >&2
    exit 1
fi

echo "[smoke] PASS"
